from enum import Enum

class GlobalErrorMessages(Enum):
    CREATE_PUPIL_FAILED = "❌ Ошибка создания ученика:"
    RETRY_FAIL = "❌ Ошибка подписки:"
    FREEZING_ALREADY_EXISTS = "⚠️ Заморозка уже существует на дату"
    FREEZING_FAILED = "❌ Ошибка при заморозке:"
    FREEZING_DATE_MISMATCH = "❌ Дата заморозки не совпадает:"
    PUPIL_DID_NOT_RECEIVE_MESSAGE = "❌ Ученик не получил сообщение"
    MENTOR_DID_NOT_RECEIVE_MESSAGE = "❌ Ментор не получил сообщение от ученика"
    EMPLOYEE_CREATION_FAILED = "❌ Ошибка создания сотрудника:"
    MENTOR_CREATION_FAILED = "❌ Ошибка создания ментора:"
    FIELD_MISMATCH = "❌ Поле не совпадает"
    USER_ID_NOT_FOUND = "❌ userId не найден"
    USER_NOT_FOUND_IN_RESPONSE = "❌ Ученик не найден в ответе"
    USER_NOT_FOUND_IN_LIST = "❌ Ученик с номером {phone} не найден в списке"
    INVALID_NAME = "❌ Неверное имя"
    INVALID_PHONE = "❌ Неверный номер"
    INVALID_USER_ID = "❌ Неверный userId"
    SUBSCRIPTION_NOT_FOUND = "❌ Подписка {subscription} не найдена"
    RESPONSE_NOT_LIST = "❌ Ответ не является валидным списком"
    RESPONSE_STATUS_ERROR = "❌ Ошибка: {status} - {body}"